README.md
Most uppercase first functions in JavaScript are considered as constructors to be used with new Constructor().
http://jslinterrors.com/a-constructor-name-should-start-with-an-uppercase-letter
=> Helper => helper

README.md, bower.json
So that it can be used as `algoliasearch`.
Note that I put an `algoliasearch:3.x` dependency.
=> Add bower.json file

examples/instantsearch+helper+excludes.html, examples/instantsearch+helper.html, src/algoliasearch.helper.js, test/spec/helper.events.js, test/spec/search.js
In order to clarify the API for the users, this pull requests changes the following : 
- no automatic search on state changes
- no more hold search parameter to prevent this behavior
- chainable mutation api to ease the use
- separate genuine search from setting the query
=> Fix #41 : rm holdSearch non sensible API

CHANGELOG, src/SearchParameters/index.js, src/algoliasearch.helper.js, test/spec/helper.clears.js
Designed to provide a first answer to #25.
Added 4 internal functions :
- clearFacetRefinements
- clearDisjunctiveFacetRefinements
- clearExcludeRefinements
- clearNumericRefinements
Each of them can clear everything but also be limitted by `name`.
It doesn't change how `helper.clearRefinements()` works, but
adds `helper.clearRefinements( name )` will search and remove
the refinements of a given facet / attribute.
=> Clear refinements by name

src/SearchParameters/index.js, src/algoliasearch.helper.js, test/spec/SearchParameters.getRefinedDisjunctiveFacets.js, test/spec/SearchResults.getFacet.js, test/spec/refinements.js
The ability to declare a numeric attribute as a disjunctive facet makes it easy to create sliders in instant search implementations.
=> Fix #53 : handle numeric filters for attributes declared as disjunctive facets

CHANGELOG, package.json, test/integation-spec/helper.filters.js, test/run.js, test/spec/helper.facetFilters.js, test/spec/refinements.js
This PR is not a new feature. It tests that the feature is actually there. The tests implemented cover the different aspects required for the feature : SearchParameters can use many refinements for a single conjunctive facet, that those refinements lead to correct filtering in the query for the js client and finally that we get the expected results from Algolia engine.
It also provides the framework for integration testing with Algolia engine.
Special thanks to @vvo for the help on the integration tests ;)
=> Fix #51 : conjunctive facets with multiple filtering

src/SearchParameters/index.js, test/spec/helper.clears.js
Let the user use a function to clear specific refinements.
Will go through all the refinements, and call the user function with the parameters : 
- value : for numeric the value and the operator, otherwise just the facet value
- attribute : the attribute the refinement is applied on
- type : the type of refinement
=> FIX #25 Advanced clear refinement

src/SearchParameters/RefinementList.js, src/SearchParameters/index.js, src/algoliasearch.helper.js, test/spec/refinements.js
Use case : 
- user input a number as a facet filter
- algolia returns string for facet values
- user can't loop over the values to check if they are refined because on one side the value is a string, and on the other the value is a number, making the comparison false.
In this fix, the lib will always convert any input value for the filters to strings. This will apply to conjunctive, disjunctive and exclude refinements.
=> Fix #106 Convert facet value to string

src/SearchParameters/index.js, src/algoliasearch.helper.js, test/spec/helper.numericFilters.js
hasRefinements now test if a given attribute contains a numeric filter too.
=> FIX #110 : provide a way to test if an attribute is numerically defined

index.js, package.json, scripts/lint.sh, src/SearchParameters/RefinementList.js, src/SearchParameters/index.js, src/SearchResults/index.js, src/algoliasearch.helper.js, src/functions/deepFreeze.js, src/functions/extend.js, test/integration-spec/helper.filters.js, test/integration-spec/helper.highlight.js, test/integration-spec/helper.tags.js, test/spec/SearchParameters.noChanges.js, test/spec/SearchParameters.setQueryParameter.js, test/spec/SearchParameters.setQueryParameters.js, test/spec/SearchResults.getFacet.js, test/spec/helper.clears.js, test/spec/helper.distinct.js, test/spec/helper.facetFilters.js, test/spec/helper.getQueryParameter.js, test/spec/helper.numericFilters.js, test/spec/helper.pages.js, test/spec/helper.queryID.js, test/spec/helper.setQueryParameter.js, test/spec/helper.tags.js, test/spec/refinements.js, test/spec/search.js, test/spec/search.testdata.js, zuul.config.js
- upgrade eslint configuration to latest (some spacing were not consistent)
- created [algolia/jsfmt](https://github.com/algolia/jsfmt) that can rewrite a whole project according to our style
- add an `npm run jsfmt` script
- run `jsfmt --diff` as part of the linting, so that when code style is not conform, we error. Most of the time, fixing the ESLint errors should get you out of the way of jsfmt.
- If you just want to reformat at any point, do `npm run jsfmt`
Also
```sh
npm install @algolia/jsfmt -g
```
To use it anywhere in any project.
=> style: run jsfmt on current code

CHANGELOG, README.md, package.json, src/SearchParameters/index.js, src/SearchResults/generate-hierarchical-tree.js, src/SearchResults/index.js, src/algoliasearch.helper.js, test/spec/hierarchical-facets/breadcrumb.js, test/spec/hierarchical-facets/custom-separator.js, test/spec/hierarchical-facets/no-refinement.js, test/spec/hierarchical-facets/no-trim.js, test/spec/hierarchical-facets/one-level.js, test/spec/hierarchical-facets/simple-usage.js, test/spec/hierarchical-facets/simple.js, test/spec/hierarchical-facets/two-facets.js, test/spec/hierarchical-facets/unknown-facet.js, test/spec/search.js, test/spec/search.testdata.js
I have implemented the hierarchical facets as proposed in #137.
The available API is: (different from proposal)
Given records like this:
```json
{
"name": "Flying dog easy IPA",
"categories": {
"lvl0": "beers",
"lvl1": "beers > IPA",
"lvl2": "beers > IPA > Flying dog"
}
}
```
When using the helper:
```js
var helper = algoliasearchHelper(client, indexName, {
hierarchicalFacets: [{
name: 'categories', // mandatory
attributes: ['categories.lvl0', 'categories.lvl1', 'categories.lvl2'] // mandatory, because we cannot guess what's the maximum level is (different from proposal)
separator: '>' // optionnal, default to '>'
}]
});
helper.toggleRefine('beers > IPA > Flying dog');
helper.on('result', function(content) {
console.log(content.hierarchicalFacets);
// [{
//   'name': 'categories',
// …
```
=> feat: hierarchical facets

src/SearchParameters/index.js, src/algoliasearch.helper.js, test/spec/SearchParameters.noChanges.js, test/spec/helper.clears.js, test/spec/helper.distinct.js, test/spec/helper.excludes.js, test/spec/helper.incorrectFacetDefinition.js, test/spec/helper.pages.js, test/spec/refinements.js
For example if a facet is declared as disjunctive and we use `addRefine` with it then it should throw an exception.
=> Fix #116 : a facet declared incorrectly should throw exceptions 

src/SearchParameters/index.js
This is to allow some of our clients using these params to send them to our servers.
=> fix: add undocumented offset and length params

src/SearchParameters/index.js, test/spec/unknown-parameter.js
Not sure we should merge this or should we wait for V3.. Because this
could break a good number of implementations..
=> fix: throw when unknown parameter

src/algoliasearch.helper.js
jsdoc is showing deprecated methods as members (and thus at first in
the page).
This change will revert this and hide them from members (still shown
as methods, with deprecated indication).
=> chore: change the deprecated methods to avoid `members` in jsdoc

CHANGELOG, src/SearchResults/index.js, test/integration-spec/helper.filters.js, test/integration-spec/helper.highlight.js, test/integration-spec/helper.numerics.js, test/integration-spec/helper.results.getFacetValues.js, test/integration-spec/helper.searchOnce.js, test/integration-spec/helper.tags.js, test/integration-utils.js
Instead it should gracefully return an empty array (the behavior was
correctly defined for the hierarchical facets)
=> FIX #208, getFacetValues with no values for the facet should not throw.

src/SearchParameters/filterState.js
Forgot previous console.dir in the code.
=> chore: Removes console.dir

src/SearchParameters/index.js, test/spec/hierarchical-facets/pagination.js
To stay consistent with other toggle behaviors: https://github.com/algolia/instantsearch.js/issues/371
=> fix(hierarchical): reset pagination to 0 when refining

CHANGELOG, src/SearchParameters/index.js, src/SearchParameters/shortener.js, test/spec/SearchParameters.numericAttributes.js, test/spec/SearchParameters.setQueryParameter.js, test/spec/SearchParameters.setQueryParameters.js
This PR also contains : 
- adds missing attribute minProximity in SearchParameters
- updates links (were outdated)
- adds other missing parameters
- adds missing documentation for filter on SearchParameters
=> Fix #245 : hitsPerPage not parsed as a number

src/SearchResults/index.js, test/spec/hierarchical-facets/refined-no-result.js
This one occurs when no results with query + refinements and the second query with query without refinement returns result.
=> fix(hierarchicalWidget): Error when faceted and no results

src/requestBuilder.js, test/spec/search.js
Query parameter was sent twice in the query params.
=> fix(request-builder): Makes queries less ambiguous for client fix #205

src/SearchParameters/index.js, src/SearchParameters/shortener.js
Just a basic support for raw parameters as a quick fix to #262.
Should we add more support for those?
I'm thinking:
* `clearOptionalTags` to mimic `clearTags`
* `clearOptionalFacets` maybe?
* `addOptionalFacet`/`addOptionalFacets` or something similar to be able to pass an array of facet filters?
=> Feat/optionalTagFilters & optionalFacetFilters

README.md, npm-shrinkwrap.json, package.json, scripts/test-ci.sh, test/ie8-polyfill.html, zuul.config.js
IE8 is dying, but the helper can still work if you include a polyfill.
Like this:
```html
```
FTR I did not use https://cdn.polyfill.io/v2/docs/ because of a weird
"out of stack space" bug that I traced down to the Object.create
polyfill ONLY when running the tests (crazy browserify stuff
hapening).
I would say core-js seems to be working nicer and including it inside
a conditionnal comment should solve our issues.
I am looking forward simplifying our testing stack, it's currently
heavy with lot of code we do not need to be added (like tape
browserify streams etc..)
Also upgrade browserify, watchify, zuul and browzers (list of reusable browsers to test)
=> test(CI): IE8 now requires a polyfill

README.md, src/algoliasearch.helper.js
The `helper.setCurrentPage` is deprecated in favor of `helper.setPage`
=> fix(pagination): adds doc on reset behavior, changes the name of setter

test/integration-spec/helper.distinct.facet.js
This test is intended to test that if we are using distinct, the facet
that we retrieve are not filtered using distinct. FIX #272 
So basically, this adds a test without actually changing the API because the behavior is the one expected.
=> Test(distinct): tests behavior of facets using distinct

src/url.js, test/spec/algoliasearch.helper/state.js
To compare with #280 .
Here the new API consists of adding a `mapping` option to the URL methods.
The mapping would be between the current shortened version and the new one, like so:
```js
{
q: 'query',
hFR: 'hCat'
}
```
The methods which accept this new `mapping` option are:
```js
algoliasearchHelper.url.getStateFromQueryString(qs, {mapping: {hFR: 'hCat'}})
algoliasearchHelper.url.getUnrecognizedParametersInQueryString(qs, {mapping: {hFR: 'hCat'}})
algoliasearchHelper.url.getQueryStringFromState(state, {mapping: {hFR: 'hCat'}})
```
=> feat(url): new mapping option for URL methods

src/SearchParameters/index.js, src/functions/warnOnce.js, test/spec/SearchParameters/constructorFn.js, test/spec/SearchParameters/setQueryParameter.js, test/spec/SearchParameters/setQueryParameters.js
Will warn once on unknown parameters.
Fixes #200 but instead of throwing, it will accept all parameters, just warn.
=> fix(SearchParameters)Supports for unknown parameters

src/SearchParameters/filterState.js, test/spec/algoliasearch.helper/state.js
We were previously not able to filter on a hierarchical facet
attribute
=> fix(filterState): handle hierarchical facet attributes

test/spec/SearchParameters/_parseNumbers.js
Adding tests to _parseNumbers. We are going to use assign instead of
the deepClone anyway, so I removed the previous parseNumbers
suggestion.
=> test(_parseNumbers): Add tests for _parseNumbers

src/SearchParameters/index.js, test/spec/SearchParameters/_parseNumbers.js
Some number parameters can also have string values. Storing number as numbers ensures that the same doesn't have 2 representations. If it's not parseable it should still be stored.
Fixes #313
=> Fix(_parseNumber): Store unparseable strings for root query parameter

src/url.js, test/spec/algoliasearch.helper/getStateAsQueryString.js
following algolia/instantsearch.js#982,
I propose to add a `safe` parameter to getQueryStringFromState that
allows you to retrieve the fully encoded url instead of a custom
encoded non-safe one.
=> feat(urls): provide a `safe` option to fully encode the url

README.md, documentation-src/build.gulp.js, documentation-src/metalsmith/content/reference.md, src/algoliasearch.helper.js, src/url.js
I've also deprecated all the query string related methods on the helper in favor of using `algoliasearchHelper.url`.
=> doc(url): document URL utilities

documentation-src/metalsmith/content/reference.md, src/SearchParameters/index.js, test/spec/SearchParameters/listAttributes.js, test/spec/SearchParameters/noChanges.js, test/spec/algoliasearch.helper/excludes.js
Let's try this again. See #327, #328, #330, #332.
@bobylito @vvo we sometimes use `conjunctive` to describe the facets defined in the `facets` attribute. Should `{add,remove}Facet` be renamed to `{add,remove}ConjunctiveFacet`?
=> feat(add-remove-facet): add methods to add and remove facets from SearchParameters configuration

documentation-src/metalsmith/content/index.md, documentation-src/metalsmith/layouts/main.jade
I tried to be more exact about the relationship of the JS Helper to other Algolia front-end tools. Beyond that, it's mostly tweaking grammar and swapping in some more common idioms.
=> Proposed copy changes on the docs home page

documentation-src/metalsmith/layouts/main.jade
Fixes small visual bug at the bottom of the home page
=> Add trailing space to avoid text running into link

documentation-src/metalsmith/stylesheets/components/_containers.scss, documentation-src/metalsmith/stylesheets/vendors/_variables.scss
So far, we were using a white for the color of the font in the hero section of the new doc. This had a poor contrast and was very bright, which led to blurry and hard to read section. This PR proposes to use a chocolate like color.
=> Update the color of the text in the hero section to improve readability

documentation-src/metalsmith/content/concepts.md, src/SearchParameters/index.js, src/algoliasearch.helper.js, test/ie8-polyfill.html
See #343.
BREAKING CHANGE: SearchParameters methods don't reset the page to 0 anymore.
=> feat(no-set-page): don't reset the page to 0 in SearchParameters methods

src/SearchResults/index.js
Document why the number of facets returns by getFacetValues might be >
than the number asked with maxValuesPerFacet.
Fix #187
=> doc(getFacetValues) number of facets > maxValuesPerFacet

src/algoliasearch.helper.js, test/spec/algoliasearch.helper/searchOnce.js
There was an undefined error occurring when attempting to construct a `SearchResults` when there was no results (because of an error). This adds some falsey checking to ensure that results are present before constructing.
=> #399: Passing null for results to callback when err present

src/algoliasearch.helper.js, src/requestBuilder.js, test/integration-spec/helper.searchForFacetValues.js, test/integration-utils.js
This new method on the helper lets a user search into facet values. The function takes the attribute and the query as parameters, and it returns a promise of the content of the search. Because this method is implemented on the helper, it takes also the current context / state: all the facets and parameters will be sent with the query. Also the returned value is altered to add an `isRefined` attribute so that we know if the value is already selected.
_A note on facets_
If the searched facet is conjunctive, the filters that are already set on it will be sent - whereas if the facet is disjunctive, the filters on this facet won't be sent.
Given that we the following dataset:
```js
[
{objectID: '1', f: 'ba', f2: ['b']},
{objectID: '2', f: 'ba', f2: ['c', 'x']},
{objectID: '3', f: 'ba', f2: …
```
=> feat(searchForFacetValues): implement a new method to be able to search into facet values

src/algoliasearch.helper.js, test/spec/algoliasearch.helper/instanciate.js
This was causing problems with users who are not upgrading their JS
Helper, but not their client.
=> fix(agent): Add a test if addAlgoliaAgent exists

src/algoliasearch.helper.js
DerivedHelper fires `result` event, not `results`.
=> doc: Fix typo

src/SearchResults/index.js, test/spec/search.testdata.js
This PR aims to expose the content `mainSubResponse` inside `SearchResults` in order to have the raw Algolia JSON response available in our JS application.
Here's some more context about it: in our dashboard we would like to display a raw Algolia JSON response like the following:
Currently this is not easily achievable by solely using the Helper, as the original, pre-parsed request is not available.
I'm not sure this is the best way to go or if it would be better to optionally expose the field. Any thoughts on this @bobylito?
=> feat(search-response): Exposed raw response

src/algoliasearch.helper.js, src/requestBuilder.js, test/integration-spec/helper.searchForFacetValues.js
Adds the support for the `maxFacetHits` parameter that limits the number
of items returned by the search for facet value API.
Fixes #480 
cc @seafoox
=> feat(maxFacetHits): implement maxFacetHits for SFFV

package.json, yarn.lock
`marked` is listed as a dependency, but is only used as a devdependency when making the documentation site.
Because I ran `yarn remove` and `yarn add`, other dependencies seem to have been changed since last time `yarn` has been run.
=> chore(pkg) move marked to devDep

documentation-src/metalsmith/content/gettingstarted.md, index.html, src/SearchParameters/RefinementList.js, src/SearchParameters/index.js, src/SearchResults/index.js, src/algoliasearch.helper.js
I have spelling detection enabled in my editor, and it complained that there were a few typos, so I fixed them.
There's one typo I can't really fix or I'm not sure if it's worth it since it changes a parameter.
There's `...Sizefor...` in a few attributes that should be `...SizeFor...`.
=> docs(jsdoc): fix spelling

src/SearchResults/index.js
Add missing `}` in example [in SearchResults section](https://github.com/algolia/algoliasearch-helper-js/blob/789f0430bd2945f93bba04a5540355abfdb889fb/src/SearchResults/index.js#L605).
=> Fix example in SearchResults/index.js

src/algoliasearch.helper.js
Move code around to make sure that we both have a proper event order with `searchQueueEmpty` after `result` or `error`.
=> misc(event-order): single event statement

src/algoliasearch.helper.js
This is a fix for #502 .
Let me know if you need more context.
Not sure how to test it. Any help would be more than welcome.
Here is what I want to achieve:
```js
new Promise(resolve => {
if (this._helper.hasPendingRequests() === false) {
return resolve();
}
// Todo: we need to de-register the one that is not being triggered.
this._helper.once("searchQueueEmpty", () => {
resolve();
});
this._helper.once("error", error => {
throw new Error(error.message);
// Todo: implement rejection once this has a solution
// https://github.com/algolia/algoliasearch-helper-js/issues/502
// reject(error);
});
});
```
=> fix(pending-search): dispatch error event before searchQueueEmpty

src/url.js
Before the query string generated was: `query=a&`
now: `query=a`
=> fix(url): When there are no "other attributes" should not render last &

src/SearchResults/index.js
The `FacetValue` type is wrongly documented as having a `value` attribute, when it actually is called `name`
(see [relevant code](https://github.com/algolia/algoliasearch-helper-js/blob/master/src/SearchResults/index.js#L541-L548))
=> fix(FacetValue doc): wrong attribute name in docs

src/algoliasearch.helper.js, test/spec/algoliasearch.helper/state.js
**Bug:**
When you call `helper.setState()` it won't compute `hierarchicalFacets` to check if there is a `rootPath` defined to set a `hierarchicalFacetRefinement`.
=> fix(setState): use .make() instead of constructor()

documentation-src/metalsmith/content/reference.md, src/SearchResults/index.js, yarn.lock
userData is a field that can be populated through the use of query rules. Until now it was only available by accessing the _rawResults object. Now it is accessible directly on the SearchResults.
fix #529
=> feat(query rules): expose userData

package.json, src/SearchParameters/RefinementList.js, src/SearchParameters/index.js, src/algoliasearch.helper.js, test/run.js, test/spec/SearchParameters/RefinementList/clear.js, test/spec/SearchParameters/_clearNumericRefinements.js, test/spec/algoliasearch.helper/clears.js, test/spec/algoliasearch.helper/events.js, test/spec/algoliasearch.helper/numericFilters.js
In order to fix this issue, we needed to actually fix two things:
- make sure that the mechanics in the Helper, check if there is a `change` and not trigger all the time. This implies a refactoring on the Helper side of all the mutating methods and make sure that before triggering the change event, we check the changes.
- make sure that we are able to determine that there has been a change. This implies to verify that all updating methods on the searchParameters are not returning new instance of the state if this is not necessary.
The first point was pretty easy to implement. For the second, it was trickier. The clears were not scarce at all.
Also please the implementation of the _clearRefinements and clear (in refinementList), the usage with function will create a new structure but will …
=> fix(events): only trigger change when there is an actual change

src/algoliasearch.helper.js, test/integration-spec/helper.searchForFacetValues.js, test/spec/algoliasearch.helper/searchForFacetValues.js
Until now it was not possible to update the state before searching for a facet value. But this can be annoying to not be able the search state that is sent to Algolia. This PR adds a new parameter to the method.
It does make for a great looking API but I didn't want to make a breaking change.
This PR is required for https://github.com/algolia/instantsearch.js/issues/2474
=> feat(sffv): can override search when using searchForFacetValues

.npmignore, package.json
Right now all files in the directory are published to npm on publish. On the [Yarn site](https://yarn.pm/algoliasearch-helper) you can check which files are included now, which includes the documentation and other files. 
Also removes the .npmignore file, since a whitelist is better than a blacklist
=> chore(package.json): add files entry

src/SearchParameters/index.js, test/spec/SearchParameters/_parseNumbers.js, test/spec/algoliasearch.helper/state.js, test/spec/url.js
fixes #553
There's two representation of insideBoundingBox, one is `'47.3165,4.9665,47.3424,5.0201'`, the other is `[[47.3165, 4.9665,47.3424, 5.0201], [40.9234, 2.1185, 38.6430, 1.9916]]`. If URLSync was
used with the second form, it would be parsed as `[ ["51.1241999","9.662499900000057", "41.3253001", "-5.559099999999944"] ]` instead of the original array of array of floats.
This commit adds special handling for this kind of shape to the `_parseNumbers` of `SearchParameters`
=> fix(url): treat insideBoundingBox in float form as number

scripts/release.js
There is a missing step in the release process: the build step. This patch adds this step using the existing script.
=> fix(release-script): actually build the library

test/run.js
=> chore(test): delete all generated indices at the end of the tests

src/algoliasearch.helper.js, test/spec/algoliasearch.helper/searchForFacetValues.js
This PR adds usage of `client.searchForFacetValues(query[])` over `client.initIndex('indexName').searchForFacetValues(query)` when available.
Related feature in the client: algolia/algoliasearch-client-javascript#677
=> feat(sffv): Use client SFFV over index SFFV

src/SearchParameters/index.js, src/SearchResults/index.js, src/functions/valToNumber.js, src/requestBuilder.js, src/url.js
This function is deprecated, and all it exports is Array.isArray anyway.
Won't have a significant impact on bundle size, but it's at least less to think about :)
Array.isArray is supported in IE9+ as we do with the rest of the helper (and we already used it in some places)
=> refactor(lodash): don't use lodash/isarray

src/algoliasearch.helper.js, test/spec/search.js
**Summary**
With the latest client (`3.28.x`) we can now cache the request rather than the response (see [#694](https://github.com/algolia/algoliasearch-client-javascript/pull/694)) This new option is disabled by default. When it's enabled the shape of the cache is a bit different than before:
```ts
type Response = {
body: object;
responseText: string;
};
type Cache = {
[cacheID: string]: Promise<Response>;
};
```
With the body inside the cache when we update its reference (mutate it) we also modify the value in the cache. It doesn't have an impact on the next response serve by the client because we don't use the `body` for the cached requests. We use the `responseText` in that way we always return the original response. But in case the `body` is modified the we have an inconsistencies …
=> fix(algoliasearch): avoid mutate the client response

documentation-src/metalsmith/content/gettingstarted.md
The former link no longer exists, now the InstantSearch tutorial is in the Getting Started guide.
=> docs: fix broken link

documentation-src/metalsmith/content/concepts.md
Added a missing "r" to hierarchical facets, as pointed out from a customer: https://secure.helpscout.net/conversation/804189820/129600?folderId=1106367
=> docs: fix typo on hierarchical facets

package.json, scripts/build.sh, yarn.lock
this creates two new files:
```
//# sourceMappingURL=algoliasearch.helper.js.map
//# sourceMappingURL=dist/algoliasearch.helper.min.js.map
```
- add exorcist for having the source map via browserify (otherwise only inline)
- add appropriate options for uglifyJS
Further nothing is changed. This setup is compatible with `source-map-explorer`
IFW-622
=> chore(build): add source map support

src/algoliasearch.helper.js
could be considered as a breaking change if you're using a client version < 3.20.4 https://github.com/algolia/algoliasearch-client-javascript/commit/77b97629dbc692401c07b0d03854d6a93c57022c (and > 3.8.0, when addAlgoliaAgent was added https://github.com/algolia/algoliasearch-client-javascript/commit/3370fa48bc5dc66a84769dd19160be47597eb21e)
In the case of the older client being used, the agent will simply be injected multiple times, as was before that fix was added
=> refactor(addAgent): remove duplicate code

.travis.yml
The current Travis setup build only the `develop` & `master` branch. It's annoying with stacked PRs because the CI does not run on those. This PR removes the restrictions and build all the branches that are pushed on the project.
=> chore(Travis): build all branches

src/SearchParameters/index.js, src/algoliasearch.helper.js, test/datasets/SearchParameters/search.dataset.js, test/spec/SearchParameters/resetPage.js, test/spec/algoliasearch.helper/events.js, test/spec/algoliasearch.helper/searchOnce.js, test/spec/algoliasearch.helper/setQueryParameter.js, test/spec/algoliasearch.helper/state.js
This PR introduces a new internal method on the `SearchParameters` called `resetPage`. This function allows differentiating a "page reset" against a "regular refinement". It wasn't an issue until now because the default value for the page was `0`. We don't have default values anymore, the value is either omit or set to a value. With the previous implementation, a call to a method that resets (implicitly) the page on a `SearchParameters` that doesn't already contain a page it creates the attribute with the value 0. This is not the expected behavior. We want to let parameter without the page.
- page omit: we don't touch the instance
- page present: we reset its value to `0`
We are now able to detect a "page reset" against a "regular refinement". The `change` event now contains an additional …
=> feat: implement dedicated reset page method

src/algoliasearch.helper.js, test/spec/algoliasearch.helper/events.js
We moved the list of parameters to a single argument for the `change` event. To be consistent we have to migrate all the emitted events to the same structure. This PR takes care of the event: `searchOnce`.
=> refactor(searchOnce): emit object

src/SearchParameters/index.js, src/algoliasearch.helper.js, src/requestBuilder.js
I've been on the safe side and added defaults on places that probably already have defaults.
I didn't remove the `forEach` in URLs, because that file is removed in `next`
=> refactor(lodash): remove forEach

src/algoliasearch.helper.js, test/spec/algoliasearch.helper/derive/events.js, test/spec/algoliasearch.helper/events.js
We moved the list of parameters to a single argument for the `change` event. To be consistent we have to migrate all the emitted events to the same structure. This PR takes care of the event: `search`.
Related: https://github.com/algolia/algoliasearch-helper-js/pull/681
=> refactor(search): emit object

src/algoliasearch.helper.js, test/spec/algoliasearch.helper/events.js
We moved the list of parameters to a single argument for the `change` event. To be consistent we have to migrate all the emitted events to the same structure. This PR takes care of the event: `searchForFacetValues`.
Related: https://github.com/algolia/algoliasearch-helper-js/pull/681, https://github.com/algolia/algoliasearch-helper-js/pull/683
=> refactor(searchForFacetValues): emit object

src/SearchParameters/RefinementList.js, src/SearchParameters/index.js
As far as I can tell, the values which are arrays are always defined, even after #670
=> refactor(lodash): remove filter

src/algoliasearch.helper.js, test/spec/algoliasearch.helper/pendingSearch.js, test/spec/algoliasearch.helper/searchForFacetValues.js
Since the engine will always respond with `facetHits` on searchForFacetValues, we can assume this will always be defined.
follow-up to @samouss' comments on #674
=> test(sffv): no longer test impossible responses

src/functions/formatSort.js
The comparison is a single letter, and the first part is also a string (because it's the value from find), meaning that they can simply be compared I think
=> refactor(lodash): remove startsWith

src/SearchParameters/index.js, src/SearchResults/generate-hierarchical-tree.js, src/SearchResults/index.js, src/functions/find.js, src/functions/findIndex.js, src/functions/formatSort.js, test/spec/functions/find.js, test/spec/functions/findIndex.js
These are very naive implementations which only work on arrays, but much shorter than a real polyfill
Notable difference between the previous implementation and this one is that the `find` implementation only takes in arrays, no longer objects
=> refactor(lodash): replace find & findIndex

src/SearchResults/index.js, src/functions/compact.js, test/spec/functions/compact.js
I added tests for this function, but none of the existing real tests test that compact is needed. I'm not too sure if it really is needed in the first place.
I left it for backwards-compatibility, but all tests pass with identity instead of compact
ref for when this was added (without tests 🙌 https://github.com/algolia/algoliasearch-helper-js/pull/45/commits/744da6d1fe1c627ede06c6cfefa8d65c5a9e82b6)
=> refactor(lodash): compact

src/SearchParameters/index.js
really the replacement of forOwn is Object.entries, but that isn't fully supported, so I went with this instead.
not implementing this breaks plenty tests
=> refactor(lodash): forOwn

src/SearchParameters/RefinementList.js, src/SearchParameters/index.js, src/SearchResults/index.js, src/functions/defaultsPure.js, test/spec/functions/defaultsPure.js
The original lodash tests don't check that it also modifies the target, and as far as I can tell, we don't rely on that behaviour.
=> refactor(lodash): replace "defaults" with pure alternative

src/algoliasearch.helper.js, test/integration-spec/helper.derive.js, test/integration-spec/helper.distinct.facet.js, test/integration-spec/helper.filters.js, test/integration-spec/helper.geo.js, test/integration-spec/helper.highlight.js, test/integration-spec/helper.insights.js, test/integration-spec/helper.numerics.js, test/integration-spec/helper.results.getFacetValues.js, test/integration-spec/helper.searchOnce.js, test/integration-spec/helper.tags.js, test/spec/algoliasearch.helper/events.js, test/spec/hierarchical-facets/attributes-order.js, test/spec/hierarchical-facets/custom-prefix-path.js, test/spec/hierarchical-facets/custom-separator.js, test/spec/hierarchical-facets/do-not-show-parent-level.js, test/spec/hierarchical-facets/facet-value-length.js, test/spec/hierarchical-facets/no-refinement.js, test/spec/hierarchical-facets/no-trim.js, test/spec/hierarchical-facets/objects-with-multiple-categories.js, test/spec/hierarchical-facets/one-level.js, test/spec/hierarchical-facets/refined-no-result.js, test/spec/hierarchical-facets/show-parent-level.js, test/spec/hierarchical-facets/simple-usage.js, test/spec/hierarchical-facets/sort-by.js, test/spec/hierarchical-facets/two-facets.js, test/spec/search.js
We moved the list of parameters to a single argument for the `change` event. To be consistent we have to migrate all the emitted events to the same structure. This PR takes care of the event: `result`.
Related: https://github.com/algolia/algoliasearch-helper-js/pull/681, https://github.com/algolia/algoliasearch-helper-js/pull/683, https://github.com/algolia/algoliasearch-helper-js/pull/684
=> refactor(result): emit object

src/algoliasearch.helper.js, test/integration-spec/helper.distinct.facet.js, test/integration-spec/helper.filters.js, test/integration-spec/helper.numerics.js, test/integration-spec/helper.searchOnce.js, test/integration-spec/helper.tags.js, test/spec/algoliasearch.helper/events.js
We moved the list of parameters to a single argument for the `change` event. To be consistent we have to migrate all the emitted events to the same structure. This PR takes care of the event: `error`.
Related: https://github.com/algolia/algoliasearch-helper-js/pull/681, https://github.com/algolia/algoliasearch-helper-js/pull/683, https://github.com/algolia/algoliasearch-helper-js/pull/684, https://github.com/algolia/algoliasearch-helper-js/pull/699
=> refactor(error): emit object

README.md, documentation-src/metalsmith/content/gettingstarted.md, documentation-src/metalsmith/content/reference.md, index.js, src/SearchResults/index.js, src/algoliasearch.helper.js
We moved the list of parameters to a single argument for the `change` event. To be consistent we have migrated all the emitted events to the same structure. This PR takes care of updating the documentation for the signature of those events.
Related: https://github.com/algolia/algoliasearch-helper-js/pull/681, https://github.com/algolia/algoliasearch-helper-js/pull/683, https://github.com/algolia/algoliasearch-helper-js/pull/684, https://github.com/algolia/algoliasearch-helper-js/pull/699, https://github.com/algolia/algoliasearch-helper-js/pull/700
=> docs: update event signature

src/SearchResults/generate-hierarchical-tree.js, src/SearchResults/index.js, src/functions/orderBy.js, test/spec/functions/orderBy.js
I generated this code:
1. take original lodash code
2. inline imports
3. inline helpers
4. remove edge-case helpers (string instead of array arguments, path instead of element, Symbol support, NaN support etc.)
5. copy tests from lodash
6. change tests to work in Jest
7. remove one test that no longer would have passed
This probably can be simplified a bit more here and there, but likely isn't that important
=> refactor(lodash): replace orderBy

src/SearchParameters/RefinementList.js, src/SearchParameters/filterState.js, src/SearchParameters/index.js, src/SearchResults/index.js, src/algoliasearch.helper.js, src/functions/objectHasKeys.js, src/functions/valToNumber.js
- isUndefined
- isEqual
- isNaN
- keys
- isFunction
- isEmpty
=> refactor(lodash): remove simple functions

src/functions/formatSort.js, test/spec/functions/formatSort.js
This was noticed in https://github.com/algolia/algoliasearch-helper-js/pull/690#discussion_r282467917 by @samouss, so I took the time to rewrite this function a little bit to be more clear (IMO)
=> fix(sortBy): compare whole prefix instead of first character

src/SearchParameters/index.js, test/spec/SearchParameters/constructorFn.js, test/spec/SearchParameters/setQueryParameters.js
This PR updates the internals of the `SearchParameters` to avoid `undefined` values inside the search parameters. This change allows to easily merge multiple `SearchParameters` top-down since we don't have "ghost" value on the object. The outcome is the change of semantics for the parameters and setters:
- `query is omit`: params does not have query e.g. `searchBox` not mounted
- `query: ''`: params does have an empty query e.g. `searchBox` mounted with initial state
- `query: 'Apple'`: params does have a query refinement e.g. `searchBox` mounted with refinement
-----
- `setQuery()`: omit the query e.g. `widget.dispose`
- `setQuery('')`: sets the default value for the query e.g. `widget.getConfiguration`
- `setQuery('Apple')`: sets the given value for the query e.g. `widget.refine`
=> feat(SearchParameters): avoid undefined values

src/algoliasearch.helper.js, test/spec/algoliasearch.helper/derive/multiqueries.js
This PR introduces a new method called `searchOnlyWithDerivedHelpers`. As the name suggests the function allows to bypass the "main" instance search to only use the Derived Helpers. The main idea behind the API is to be able to control which state is used by the query, without having to alter the internal state of the helper (it would be useful for federated search for example). With the `.derive` API we have a full control on the query with the derivation function. We can alter the state without impact on the internal instance of the Helper.
I choose to implement this behavior with a dedicated method to limit the number of changes. We'll release a major version but we should keep the support of the original behavior because it will not only benefit InstantSearch.js. We also want to …
=> feat(search): allow the search only with Derived Helpers

README.md, documentation-src/metalsmith/content/reference.md, src/algoliasearch.helper.js, test/datasets/SearchResults/getFacetValues.dataset.js, test/datasets/SearchResults/getRefinements.dataset.js, test/spec/algoliasearch.helper/state.js
You can always retrieve the state as `helper.state`, so there's no need for `helper.getState()`. See https://github.com/algolia/instantsearch.js/pull/3774 for the removal of this in InstantSearch (React didn't use this function)
BREAKING CHANGE: use helper.state instead of helper.getState()
=> feat(getState): remove getState

package.json, yarn.lock
It's still required for some tests etc., so it's kept in devDependencies
(blocked by #694)
closes #552
=> chore(lodash): remove lodash from dependency list

src/SearchResults/index.js
This is a basically useless response, and we maybe should remove it, and similar field (as you can read them from _rawResponse), or we can arbitrarily set all remaining parameters.
(PR is on `next` so we can discuss the removal without needing to change the base)
fixes #500
=> docs(serverUsed): mention getRankingInfo

package.json, scripts/release.js, yarn.lock
This PR allows to release a "canary" version of the package. 
The version follows this format: `0.0.0-SHORT_SHA-1` where `SHORT_SHA-1` is the hash of the latest commit. The version is then published on npm with the tag `canary`. The command does not update the CHANGELOG or create a Git Tag. The usage of the version is mostly internal. Its purpose is to publish a non-stable version that can be used directly from other projects via npm (useful for the CI).
At some point, we might want to port the process on other projects as well. It would allow us to test packages directly from E2E tests or even on example projects that we maintain. I didn't use it (yet) to publish a version (I did test it though with the `pack` command). I'll do it once the PR is approved and merged.
=> chore(release): allow canary release

src/functions/merge.js, test/spec/functions/merge.js
- split the implem into merge(target, ...sources) and _merge(target, source), I think it's more simple this way.
- I reorganized some of the conditions
The description and the test suit should not change. Implementation has changed but behaviour and limitation are the same (Note that the lodash inspired test suite for merge should be passing).
Other minor change to note: use .toStrictEqual instead of .toEqual in tests
closes https://github.com/algolia/algoliasearch-helper-js/pull/714  https://github.com/algolia/algoliasearch-helper-js/pull/709
=>  fix(merge): change implementation 

src/SearchParameters/index.js, test/spec/SearchParameters/isHierarchicalFacetRefined.js
Similar to #727, except here we _do_ need to keep throwing the error on add
see #722
=> fix(isHierarchicalFacetRefined): return false if refinement isn't a facet

src/algoliasearch.helper.js, test/spec/algoliasearch.helper/incorrectFacetDefinition.js, test/spec/refinements.js
This method is now throwing an error when nothing is refined, while really it should be false like `hasRefinements`. Because of the other inconsistencies & the fact that it's deprecated, we are removing it
see #722
BREAKING CHANGE: removed helper.isRefined, use helper.hasRefinements instead
=> fix(errors): remove isRefined

index.d.ts, src/SearchParameters/index.js, test/spec/hierarchical-facets/breadcrumb.js
Funnily enough, this test didn't fail becuse the bind always threw
We return an empty array if the facet wasn't declared
see #722
=> fix(getHierarchicalFacetBreadcrumb): don't throw an error

src/SearchResults/index.js, test/spec/SearchResults/getFacetStats.js
This now should also return `undefined` without warning, like #720
see #722
=> fix(getFacetStats): remove error

index.d.ts, src/SearchResults/index.js, test/spec/SearchResults/getFacetValues.js
connectMenu could throw if a facet is retrieved which isn't in the SearchParameters, but we are changing that to return undefined in those cases.
This is part 1 of the big error removal process.
see algolia/instantsearch.js#3084
see #722
=> fix(getFacetValues): don't throw error when there's no facet

src/SearchParameters/index.js, test/spec/SearchParameters/getDisjunctiveRefinements.js
The condition is there to prevent a refinement of a non-declared facet, however we should just return the empty state there instead ([]).
See #722
=> fix(getDisjunctiveRefinements): remove error

src/SearchParameters/index.js, test/spec/SearchParameters/getConjunctiveRefinements.js
Instead we will return [] there.
see #722
=> fix(getConjunctiveRefinements): no error when requested facet is not conjunctive

src/SearchParameters/index.js, test/spec/requestBuilder.js
We are now moving towards passing empty arrays to refinements; so we need to make sure no extra requests are done.
=> feat(requestBuilder): prevent needless extra requests for empty refinements

src/SearchParameters/RefinementList.js, src/SearchParameters/index.js, src/SearchResults/index.js, test/spec/SearchParameters/numericFilters.js, test/spec/SearchParameters/removeXFacetRefinement.js, test/spec/algoliasearch.helper/clears.js, test/spec/algoliasearch.helper/excludes.js, test/spec/algoliasearch.helper/numericFilters.js, test/spec/refinements.js
When clearing a refinement using `toggleRefinement` we want to keep the empty refinement object for that attribute, because we use it to override a deeper refinement of that attribute in IS.js with federated search
=> fix(toggleRefinement): keep an empty array when clearing

src/SearchParameters/RefinementList.js, src/SearchParameters/index.js, test/spec/SearchParameters/RefinementList/clear.js, test/spec/SearchParameters/removeXFacet.js, test/spec/algoliasearch.helper/clears.js
This does not have an averse on the toggle methods, which should keep empty arrays.
required for https://github.com/algolia/instantsearch.js/pull/4024
=> fix(removeXFacet): make sure this fully removes empty arrays

src/SearchParameters/index.js, test/spec/SearchParameters/hierarchical-facets/remove.js
This used to throw an error when nothing is refined, but that's inconsistent with the other refinements.
See https://github.com/algolia/instantsearch.js/blob/9e4dda512f3ceddf42d59101a1cc6b34aba70e1d/src/lib/utils/clearRefinements.ts#L26 for a reason to change this.
=> chore(removeHierarchicalFacetRefinement): remove error if not refined

index.d.ts
This adds the missing [`sumOrFiltersScores`](https://www.algolia.com/doc/api-reference/api-parameters/sumOrFiltersScores/) search parameter type.
=> chore(types): add `sumOrFiltersScores` search parameter

index.d.ts
This adds the missing [`optionalFilters`](https://www.algolia.com/doc/api-reference/api-parameters/optionalFilters/) search parameter type.
=> fix(types): add `optionalFilters` search parameter

.circleci/config.yml, package.json, test/integration-utils.js, test/run.js, test/spec/algoliasearch.helper/client.js, yarn.lock
This pull requests adds the same changes as: https://github.com/algolia/algoliasearch-helper-js/pull/756 to the helper v2.
We are doing this change because vue-instantsearch rely on this helper v2.
=> feat(algoliasearch): add support for algoliasearch v4 the helper v2

.circleci/config.yml, index.d.ts, package.json, test/integration-utils.js, test/run.js, test/spec/algoliasearch.helper/client.js, yarn.lock
This change add support for algoliasearch v4 to algoliasearch helper.
No changes were necessary in the code. The test suite was updated to support both v3 and v4 versions of algoliasearch client. We also added a new job to CircleCI to test the version 4 of the client.
=> feat(algoliasearch): add support for algoliasearch v4 the helper v3

src/SearchParameters/RefinementList.js, src/SearchParameters/index.js, test/spec/SearchParameters/RefinementList/clear.js, test/spec/SearchParameters/_clearNumericRefinements.js
The `omit` function is meant to be called with an array of key to exclude.
```js
omit ({
"Brand": ["HP"],
"CPU type": ["Core i5"],
"Motherboard CPU type": ["Intel Core X"]
},  ["Motherboard CPU type"]);
// -> {"Brand": ["HP"], "CPU type": ["Core i5"]}
```
Calling it with a string also works but can have an undesired behavior and exclude some keys that matches a substring of the one we want to exclude.
```js
omit ({
"Brand": ["HP"],
"CPU type": ["Core i5"],
"Motherboard CPU type": ["Intel Core X"]
},  "Motherboard CPU type");
// -> {"Brand": ["HP"]}
```
This is because in that case we're doing an [`.indexOf`](https://github.com/algolia/algoliasearch-helper-js/blob/80d755c720419f5800557cc89e314cbf24ff0430/src/functions/omit.js#L12) on a string instead of on an array.
With a string:
```js …
```
=> fix: fix omit calls to pass excluded value as an array

src/functions/defaultsPure.js, test/spec/SearchResults/getFacetValues.js, test/spec/functions/defaultsPure.js
See #761 for issue, thanks!
I'm computing an array of keys in the order they come from sources, then using it with `mergedSources` to return a new _keys-order-preserved_ object.
=> fix(defaultsPure): don't change keys order, fix #761

index.d.ts
[We often rely on the `resetPage` method](https://github.com/algolia/instantsearch.js/blob/5ff4c8307c2be7bde7fb53aa9935a243e6532fe2/src/widgets/index/index.ts#L146) which was untyped.
=> fix(types): add `resetPage` state method

index.d.ts
We are doing some tricky things here by using [Conditional Types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#conditional-types) to keep this library compatible with [`algoliasearch`](https://github.com/algolia/algoliasearch-client-javascript) v3 and v4.
But since 3.9 TypeScript is not able to statically analyze our code anymore to determine the `SearchOptions` and `SearchResponse` types (https://github.com/algolia/algoliasearch-helper-js/issues/774) :sob: 
This PR fixes this by using directly `ReturnType<typeof algoliasearch>` instead of the `Client` type. With this notation the static analyze seems to work with no issues again.
fixes #774
=> fix(typescript): fix TypeScript 3.9 compatibility (fixes #774)

src/SearchResults/index.js, test/datasets/SearchParameters/search.dataset.js
This PR updates SearchResults to expose all the fields from the search API response implicitly.
It used to manage an allow-list. I've removed it and only computed properties are added on top of that. It means if search API adds a new field, it might be overridden by the computed property if their names are the same.
Do you see any improvements that can be made? cc @Haroenv
=> fix: accept all fields implicitly instead of the allow list

src/SearchParameters/index.js, test/spec/SearchParameters/_parseNumbers.js
If you set an invalid parameter, like `insideBoundingBox: [123,123,123,123]`, an error was thrown, since it's not a nested array. We shouldn't fix this case, but rather let the API return an error which is more easy to catch.
The example in the test, as well as the one from the original issue `[42.3435822,-122.879144, 37.2967792, -121.9574956]` both throw an error in the engine, as well as here, before this PR.
The reason for leaving them alone, instead of trying to fix by adding in array, is that the API could change what they accept in the future, and this way we will not need to adapt. Additionally, an error response is easily caught with InstantSearch, vs. a TypeError in the Helper, which throws outside of React life cycles
=> fix(insideBoundingBox): prevent invalid parameter from throwing

index.d.ts
Since the type definition of `@types/algoliasearch` also has `addAlgoliaAgent`, it actually took the v4 imports, which turn out to be "any". Since the change in https://github.com/algolia/algoliasearch-helper-js/pull/775 showed this behaviour more clearly, I found a solution to use a dedicated key which only exists in v4 (transporter) to distinguish between the versions
=> fix(ts): use a dedicated key to determine client version

package.json, patches/metalsmith-in-place+1.4.4.patch, yarn.lock
1. replace GitHub dependency with npm dependency
2. use patch-package to make the small GitHub changes
=> chore(dev): replace github dependency metalsmith-in-place

index.d.ts, src/SearchParameters/index.js
this actually returns an object, not an array!
=> fix(ts): correct type for getNumericRefinements

src/SearchParameters/index.js, test/spec/SearchParameters/_clearNumericRefinements.js
Previously this seemingly on purpose checked if this attrubte had refinements, but due to the way it is checking this, it will leave `{[attribute]: {}}` in the numeric refinements, which isn't what we want in e.g. a dispose.
related PR: https://github.com/algolia/instantsearch.js/pull/4587
Since this wasn't covered by any sort of test, I think this behaviour was unintentional
=> fix(removeNumericRefinement): clear empty refinements

index.d.ts, package.json, src/algoliasearch.helper.js, test/spec/algoliasearch.helper/findAnswers.js, yarn.lock
This PR adds `findAnswers` method.
In this way, we can apply facets to /answers call.
It doesn't emit `'result'` but returns a promise of result.
If we can replace the traditional hits with the hits from answers completely, then we should go for emitting `'result'`, but it's not the case at the moment. So I chose to return a promise.
Let me know what you think.
(I haven't added any tests because we haven't agreed on how to implement this in helper yet. Once decided here, I will add test.)
=> feat(answers): add `findAnswers`

index.d.ts
This PR makes `queryID` optionable. It's given only when `clickAnalytics: true`.
=> fix(ts): make queryID optional

index.d.ts
This PR adds the missing `relevancyStrictness` to `SearchParameters`.
=> fix(types): add relevancyStrictness to SearchParameters

index.d.ts
I've checked, and the defaulting of " > " actually happens only in `_getHierarchicalFacetSeparator`, so that means you can get facets without separator. Examples:
https://github.com/algolia/instantsearch.js/blob/1ede1ae392d3a12f5b0fe29075ffeb05e572a874/src/connectors/menu/connectMenu.js#L283-L286
https://github.com/algolia/instantsearch.js/blob/1ede1ae392d3a12f5b0fe29075ffeb05e572a874/src/connectors/menu/__tests__/connectMenu-test.js#L98-L101
=> fix(ts): correct type for HierarchicalFacet parameter

README.md
changed angular.js example link to algolia's codepen demo. currently it navigates to deleted directory
=> changed angular.js example link

index.d.ts
see https://github.com/algolia/react-instantsearch/pull/3378 for its use. As in every key of rawResults is added to the response, this does not require any code changes. You create artificial results like this: `new SearchResults(new SearchParameters(), [{ __isArtificial: true }])`
`__isArtificial` is a marker which can be added to search results to identify them as created without a search response. This is for internal use, eg. avoiding caching in infinite hits, or delaying the display of these results.
=> fix(types): allow "__isArtificial"

src/functions/escapeFacetValue.js, test/spec/SearchResults/getFacetValues.js
This wasn't fully functioning behaviour before #889 already, as numeric values don't show as refined, even if they are (see https://github.com/algolia/algoliasearch-helper-js/blob/dd375ab18513336817bd8d5d78341ac33ae94954/src/SearchParameters/RefinementList.js#L141 where it's purposely casted to a string, but the input values aren't), but it didn't throw an error, which became the case in #889
A customer discovered this in https://algolia.atlassian.net/browse/CR-883
=> fix(disjunctiveFacets): avoid escaping non-string values

index.d.ts
it takes only one argument, not two
=> fix(types): correct type for addTag

README.md
right now almost all API parameter links seem to go to https://www.algolia.com/doc/api-client/getting-started/install/ruby/?client=ruby
=> docs(readme): fixed API parameter links

src/algoliasearch.helper.js, test/spec/algoliasearch.helper/searchForFacetValues.js
client.search with `type: 'facet', facet, params: { facetQuery }` can be used in v4 onwards as an alternative to client.searchForFacetValues, meaning the client.searchForFacetValues method can be removed in a future major version.
Unfortunately the JS client v3 doesn't support type "facet" for multi-index search because it manually decides which keys are used in the post object: https://github.com/algolia/algoliasearch-client-javascript/blob/v3/src/AlgoliaSearchCore.js#L638-L654
FX-1432
=> feat(searchForFacetValues): fall back to client.search if it's present

src/requestBuilder.js, test/spec/requestBuilder.js
Having a sorted set of parameters helps with making sure the cache is hit in more cases.
For example, when you remove and immediately add the same widget again, and they no longer are in the same order, but have the same parameters conceptually.
This PR does not sort the items inside the parameters, eg. facets, which would be possible, but isn't done yet.
FX-1473
=> fix(requests): send a sorted object of parameters

src/requestBuilder.js, test/spec/requestBuilder.js
This PR reduces the amount of params sent for each disjunctive facet request.
It also reduces `hitsPerPage` from `1` to `0`, allowing us to remove the `attributes*` parameters at the same time.
This reduces:
* the payload sent by a few bytes
* and the response size by a few extra bytes as the previous implem sent back one `objectID` per additional request
=> feat(disjunctiveFacetParams): reduce payload size

index.d.ts, package.json, types/algoliasearch.d.ts, types/algoliasearch.js
Algoliasearch v5 has different type names and packages, so needs to be supported separately.
This pull request has the following changes:
1. add a folder `/types/algoliasearch` with both a .d.ts and .js file
2. add utilities and simplify the dealing of importing different types across the major versions
FX-1434
=> feat(types): support algoliasearch v5

index.d.ts, types/algoliasearch.d.ts
- Add optional typings to `SearchResults` hit and expose the `HighlightResult` `RankingInfo` and `SnippetResult` typings for use elsewhere.
- The goal is to update the `@types/react-instantsearch-core` types to use the actual `SearchResults` from `algoliasearch-helper` rather than redefining their own. `SearchResults` + `HighlightResults`, etc.
=> feat(typing): Update SearchResults hits, expose optional hit typings

index.d.ts, src/algoliasearch.helper.js
While this method still works, it's not used in InstantSearch and it no longer has any difference from a regular search, and therefore no longer needs its own function.
=> fix(answers): deprecate findAnswers

src/functions/merge.js, test/spec/algoliasearch.helper/constructor.js, test/spec/functions/merge.js
If a user-provided search parameter is used to instantiate search parameters, it was possible to construct it in such a way that `constructor.prototype` is attempted to be written. That throws an error, but if the error would be caught, the resulting injection still happened.
This PR fixes that (small) vulnerability by ensuring `constructor`, is skipped, just like `__proto__`.
fixes #922
This is similar/a follow-up to #880
=> fix: prevent prototype pollution in rare error-cases

package.json, test/integration-spec/helper.derive.js, test/integration-spec/helper.distinct.facet.js, test/integration-spec/helper.filters.js, test/integration-spec/helper.geo.js, test/integration-spec/helper.highlight.js, test/integration-spec/helper.insights.js, test/integration-spec/helper.numerics.js, test/integration-spec/helper.results.getFacetValues.js, test/integration-spec/helper.searchForFacetValues.js, test/integration-spec/helper.searchOnce.js, test/integration-spec/helper.tags.js, test/integration-utils.js, test/spec/SearchParameters/constructorFn.js, test/spec/SearchParameters/numericAttributes.js, test/spec/SearchResults/getRefinements.js, test/spec/algoliasearch.helper/clears.js, test/spec/algoliasearch.helper/distinct.js, test/spec/algoliasearch.helper/hasRefinements.js, test/spec/algoliasearch.helper/pages.js, test/spec/functions/defaultsPure.js, test/spec/hierarchical-facets/pagination.js, test/spec/hierarchical-facets/simple-usage.js, test/spec/hierarchical-facets/unknown-facet.js, test/spec/refinements.js, yarn.lock
Long time coming, but if we do a migration to monorepo, it's nice to not have a stray lodash in the devDependencies
=> chore(tests): remove remaining lodash usage

src/SearchResults/index.js, test/spec/SearchResults/getFacetValues.js, test/spec/SearchResults/getFacetValues/conjunctive.json
Before this commit, the behaviour of conjunctive/disjunctive facets and hierarchical facets is different when `results._state` has changed since the instantiation of the SearchResults class.
Conjunctive/disjunctive take the current value of `_state`, while `hierarchical` took `isRefined` from the constructor.
We want to make this change to enable optimistic UI, where we render the existing results with the next state. This causes the `isRefined` state to immediately be useful for display.
Regardless of optimistic UI, this change still makes sense to do, as it makes the behaviour of getFacetValues consistent between all types of facet.
FX-2201
=> fix(getFacetValues): reflect the value of _state in hierarchicalFacetValues

index.d.ts
A user wanted to access `queryAfterRemoval` from the results returned by `useInstantSearch`, the object does contain it, but it's missing from the types here.
[CR-2975]: https://algolia.atlassian.net/browse/CR-2975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(types): add `queryAfterRemoval` to `SearchResults`

src/algoliasearch.helper.js, test/spec/algoliasearch.helper/derive/detach.js, test/spec/algoliasearch.helper/derive/empty-index.js, test/spec/algoliasearch.helper/derive/multiqueries.js
We currently don't introspect, but if the indexName is empty, the search client will return an error, meaning skipping those queries isn't really a breaking change.
If no queries would be triggered at all, client.search is also not called.
Skipping those queries can be interesting to create patterns like "multiple sibling indices at root of instantsearch" and "orphan indices".
=> feat(DerivedHelper): skip request for empty index

src/SearchResults/index.js, test/spec/SearchResults/getRefinements.js, test/spec/SearchResults/getRefinements/exclude-artificial-results.json
This PR ensures that facet exclusions are computed from a result's facets property that is defaulted to an empty object, in case this is called with artificial results.
FX-2179
Closes #921
=> fix(SearchResults): use empty facets object for exclusion when results are artificial

package.json, types/algoliasearch.d.ts, yarn.lock
in TypeScript 5.1.3, the check `any extends T` when T is any no longer evaluates to one branch of the conditional, but the union of both branches.
This is fixed by using a "never possible to be true, unless T is any" condition as in https://stackoverflow.com/a/49928360/3185307
fixes https://github.com/algolia/instantsearch/issues/5658
FX-2396
=> fix(types): improve conditional for client version

documentation-src/plugins/jsdoc-data.js, package.json, yarn.lock
only used in the jsdoc-data plugin, and can easily be replaced without dependency
=> chore(devDeps): remove lodash.keyBy

package.json, scripts/retry.sh
The tests are sometimes flaky (integration mostly), as we're not entirely sure what the cause is, retrying seems sensible
This can also be reused in the monorepo later
=> test(unit): add retry mechanism

src/SearchResults/index.js, test/spec/SearchResults/getFacetValues.js
Just removing the `rootPath` from `currentRefinementSplit` works !
[FX-2414]: https://algolia.atlassian.net/browse/FX-2414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CR-3625]: https://algolia.atlassian.net/browse/CR-3625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(getFacetValues): ignore `rootPath` for hierarchical facets
