- package.json
Of course you are the author, but WE @algolia are the authors :)
Same author as for the JS client, what do you think?
> author update

- CHANGELOG
- dist/algoliasearch.helper.js
- examples/instantsearch+helper+excludes.html
- examples/instantsearch+helper.html
- src/SearchResults/index.js
- src/algoliasearch.helper.js
- test/spec/search.testdata.js
This impact the data structure given by the result event. In order to provide a better understanding on this structure, the construction has been moved out and the structure definition has been written down into a class.
> Make the facets sorted in the order of their definition

- CHANGELOG
- package.json
- src/algoliasearch.helper.js
- test/spec/helper.numericFilters.js
- test/spec/search.js
Add use the new search function instead of the stateful batch api.
> Fix #57 : Upgrade to algoliasearch to 3.1 and add it as peer dependency

- CHANGELOG
- src/SearchParameters/index.js
> Fix #92 parameters that can be set in the dashboard shouldn't have defaults

- index.js
- src/SearchParameters/index.js
- src/algoliasearch.helper.js
- test/spec/helper.getQueryParameter.js
> FIX #12 Add a method to get any parameter of the search

- .zuul.yml
- package.json
could not require('algoliasearch-helper')
> put envify transform only in zuul

- test/integration-spec/helper.filters.js
- test/integration-spec/helper.highlight.js
- test/integration-spec/helper.tags.js
- test/integration-utils.js
+ add debugging when it fails
+ close the underlying nodejs keep alive agent when needed (destroy)
> test: fix integration tests failures

- package.json
- src/SearchParameters/RefinementList.js
- src/SearchParameters/index.js
- src/SearchResults/index.js
- src/functions/deepFreeze.js
- test/spec/search.js
- zuul.config.js
we automatically switch to lodash-compat when building for browsers.
Thus having a lodash IE8 compatible module.
+ some adjustments
+ activate IE8 testing
> feat: IE8 compatibility

- src/SearchParameters/RefinementList.js
- test/spec/refinements.js
instead of true/undefined
fixes #123
> fix: isDisjunctiveRefined() and isRefined() return true/false

- scripts/lint.sh
- scripts/test-node.sh
- scripts/test-phantom.sh
- scripts/test.sh
Using:
```bash
set -x
```
Only for CI (travis), because it outputs too much info for devs
> chore: debug scripts only in CI

- README.md
- src/SearchResults/generate-hierarchical-tree.js
- src/SearchResults/index.js
- src/functions/formatSort.js
- test/spec/SearchResults.getFacetStats.js
- test/spec/hierarchical-facets/getFacetValues.js
- test/spec/search.js
Adds a method so that the user can access the facet values by name with sorting built-in.
Also adds a method to get the stats.
> Fix #178 : getFacetValues

- scripts/test-node.sh
> test: stop iojs testing, test on 4, 0.10, 0.12

- src/SearchResults/index.js
- test/spec/SearchResults.getFacetStats.js
> fix(facetStats): a facet can be both in facets & disjunctiveFacets

- CHANGELOG
- README.md
- index.js
- src/SearchParameters/filterState.js
- src/SearchParameters/index.js
- src/algoliasearch.helper.js
- src/url.js
- test/spec/compat.js
- test/spec/helper.state.js
- new namespace `url` for all functions related to query string serialization deserialization
- move static function to the new module
- added a new function to serialize any `SearchParameters`
- getState filter feature now exposed as filter method on `SearchParameters`
> feat(urlTools) : expose all url tools and more in a dedicated module

- src/SearchParameters/index.js
- test/spec/helper.numericFilters.js
New PR based on previous work. Added tests for untested methods, and fix the previous comments in #232 . Hi @proudlygeek @pixelastic :D
> fix(numerics) : removeNumericFilters(attribute) was not working FIX #230

- CHANGELOG
- src/SearchParameters/index.js
- src/algoliasearch.helper.js
Quick refactoring to move the auto magic toggleRefinement method from the helper to the state so that it can be used in state generation (like in the case of url generation)
> feat(SearchParameters): toggleRefinement on SearchParameters

- src/SearchParameters/index.js
- src/SearchResults/generate-hierarchical-tree.js
- test/spec/hierarchical-facets/custom-prefix-path.js
Here the implementation for #251
> feat(hierarchical): add prefix path option to hierarchical facet

- README.md
- src/SearchParameters/index.js
- src/SearchResults/generate-hierarchical-tree.js
- src/requestBuilder.js
- test/spec/hierarchical-facets/do-not-show-parent-level.js
- test/spec/hierarchical-facets/show-parent-level.js
I managed !!! :smile: 
cc @vvo
> Feat hierarchical facet root path and show parent level

- src/SearchParameters/index.js
- src/functions/valToNumber.js
- test/spec/SearchParameters/isNumericRefined.js
- test/spec/SearchParameters/numericFilters.js
- test/spec/algoliasearch.helper/numericFilters.js
- test/spec/functions/valToNumber.js
It also fixes the usage of arrays: we can now remove arrays from numeric filters.
> fix(numeric filters): Makes it possible to add then remove a string based numeric filter

- README.md
Not sure this is really needed but linked to https://github.com/algolia/algolia.github.io/issues/4
> docs(README): add a note about instantsearch.js and autocomplete.js

- scripts/docs/metalsmith/content/gettingstarted.md
Small changes, largely on punctuation.
> Make spelling and grammar changes

- src/SearchParameters/index.js
- test/spec/SearchParameters/listAttributes.js
- test/spec/SearchParameters/noChanges.js
- test/spec/algoliasearch.helper/excludes.js
> feat(add-remove-facet): add methods to add and remove facets from SearchParameters configuration

- documentation-src/metalsmith/content/reference.md
Just a little typo I spotted here
> doc(misc): typo fix

- documentation-src/metalsmith/content/reference.md
- src/SearchParameters/index.js
- src/algoliasearch.helper.js
- test/spec/hierarchical-facets/breadcrumb.js
- refactors the code for readability.
- adds tests
Fix #320
> fix(hierarchical-facets) do not throw if no refinements

- .travis.yml
- package.json
- test/perf/index.js
- test/perf/tests/instanciate.js
This provides the minimal archictecture for making perf assessment
tests. It will execute during each PR and merge on travis.
Fix #298
> test(perf) add perf test

- src/SearchResults/index.js
Let me know if I should also update this in the dist folder, but I suppose you do that when you actually release.
> Fix minor typos

- src/algoliasearch.helper.js
- test/spec/algoliasearch.helper/getQuery.js
- test/spec/algoliasearch.helper/getSearchParameters.js
> Adds a 'getSearchParameters' function to helper.

- documentation-src/metalsmith/partials/method.hbs
- documentation-src/metalsmith/partials/parameters.hbs
- documentation-src/metalsmith/plugins/handlebars-helpers.js
- package.json
> fix(doc): fix deep object documentation.

- .eslintignore
- documentation-src/metalsmith/content/reference.md
Adds a paragraph about the new method and also adds the actual reference of the method signature.
> Actually document search for facet values

- src/algoliasearch.helper.js
- test/spec/algoliasearch.helper/clears.js
- test/spec/algoliasearch.helper/distinct.js
- test/spec/algoliasearch.helper/events.js
- test/spec/algoliasearch.helper/excludes.js
- test/spec/algoliasearch.helper/facetFilters.js
- test/spec/algoliasearch.helper/getNumericRefinement.js
- test/spec/algoliasearch.helper/getQuery.js
- test/spec/algoliasearch.helper/getQueryParameter.js
- test/spec/algoliasearch.helper/getStateAsQueryString.js
- test/spec/algoliasearch.helper/hasRefinements.js
- test/spec/algoliasearch.helper/incorrectFacetDefinition.js
- test/spec/algoliasearch.helper/numericFilters.js
- test/spec/algoliasearch.helper/pages.js
- test/spec/algoliasearch.helper/queryID.js
- test/spec/algoliasearch.helper/setQueryParameter.js
- test/spec/algoliasearch.helper/state.js
- test/spec/algoliasearch.helper/tags.js
- test/spec/hierarchical-facets/add-remove.js
- test/spec/hierarchical-facets/getFacetValues.js
- test/spec/refinements.js
- test/spec/search.js
*It was supposed to be a simple job*
> misc(user-agent): Add a user agent for the JS Helper

- test/integration-spec/helper.geo.js
We didn't have any integration test for geo search. That PR adds 3
> misc(geo): add a test using geosearch

- .eslintrc
- documentation-src/metalsmith/content/reference.md
- src/algoliasearch.helper.js
- test/integration-spec/helper.searchForFacetValues.js
- test/spec/algoliasearch.helper/client.js
This is not really a feature for the users of the JS Helper, but more of
convenience for any library built on top of it.
See https://github.com/algolia/instantsearch.js/issues/1673
> feat(client): Adds methods to set/get the client.

- src/algoliasearch.helper.js
- test/spec/algoliasearch.helper/client.js
> fix(agent): sets the helper agent once

- documentation-src/metalsmith/content/reference.md
- src/algoliasearch.helper.js
- test/spec/algoliasearch.helper/events.js
> fix(events): events for all kinds of searches

- CHANGELOG
- package.json
- scripts/conventional-changelog/index.js
- yarn.lock
This is a first step towards a better integration of the release step. With that we'll have a way to update the changelog automatically :)
> chore(tooling): conventional changelog integration

- documentation-src/metalsmith/content/reference.md
- src/SearchResults/index.js
- test/spec/search.testdata.js
> fix(SearchResults): Expose exhaustiveNbHits and exhaustiveFacetsCount in SearchResults

- src/requestBuilder.js
- yarn.lock
> fix(requestBuilder): set analytics:false to subsequent queries

- test/spec/requestBuilder.js
When fixing #540, I forgot to add the tests.
> chore(test): add test for the request builder and analytics

- test/spec/algoliasearch.helper/searchForFacetValues.js
Not all tests were run, because of a forgotten test.only
> chore(test): run all tests

- src/SearchParameters/index.js
- src/algoliasearch.helper.js
- test/spec/algoliasearch.helper/getNumericRefinement.js
> chore: fix types in doc for getNumericRefinement

- src/algoliasearch.helper.js
- test/spec/algoliasearch.helper/pendingSearch.js
- test/spec/algoliasearch.helper/searchForFacetValues.js
Fix #573 
_The CI should fail since locally a test is broken on a fresh install._
> fix(sffv): unwrap content when it comes from multi queries

- README.md
fix #528 
In case this table was autogenerated from somewhere else, feel free to close this PR.
> doc(params): Add filters to query parameters

- index.js
The way this was documented throws an error
see https://codesandbox.io/s/o7k7w28n86
> docs(instantiate): use existing signature of toggleRefine

- index.js
> docs(init): use toggleFacetRefinement instead

- dist/algoliasearch.helper.js
- src/algoliasearch.helper.js
- test/spec/algoliasearch.helper/client.js
change the User-Agent to use the new specs lib (version) from `JS Helper $version` to `JS Helper (${version})`
> fix(ua): change the User-Agent to use the new specs lib (version)

- package.json
- src/SearchResults/generate-hierarchical-tree.js
- src/SearchResults/index.js
- test/spec/SearchResults/getRefinements.js
- test/spec/hierarchical-facets/attributes-order.js
- test/spec/hierarchical-facets/custom-prefix-path.js
- test/spec/hierarchical-facets/custom-separator.js
- test/spec/hierarchical-facets/do-not-show-parent-level.js
- test/spec/hierarchical-facets/facet-value-length.js
- test/spec/hierarchical-facets/getFacetValues.js
- test/spec/hierarchical-facets/no-refinement.js
- test/spec/hierarchical-facets/no-trim.js
- test/spec/hierarchical-facets/objects-with-multiple-categories.js
- test/spec/hierarchical-facets/one-level.js
- test/spec/hierarchical-facets/pagination.js
- test/spec/hierarchical-facets/refined-no-result.js
- test/spec/hierarchical-facets/show-parent-level.js
- test/spec/hierarchical-facets/simple-usage.js
- test/spec/hierarchical-facets/sort-by.js
- test/spec/hierarchical-facets/two-facets.js
This PR is the lodash looping part (which adds a new test) + adding exhaustive facet counts to hierarchical tree
It also makes the file a little simpler
> fix(hierarchical): add exhaustive & lodash looping

- src/SearchParameters/RefinementList.js
- src/SearchParameters/index.js
- src/functions/omit.js
replaced by the loose babel helper
> refactor(lodash): remove _.omit

- jest.config.js
- package.json
- yarn.lock
> chore(Jest): enable typeahead plugin

- src/SearchParameters/index.js
- Not removed from url because that will disappear later
- did both at the same time because they are too close together and would cause conflicts individually
impact: 30.6 -> 29.9
> refactor(lodash): map & trim

- src/SearchResults/index.js
- test/spec/SearchResults/initialization.js
I added a new test file, since this didn't seem to be tested anywhere.
> refactor(lodash): sumBy

- src/algoliasearch.helper.js
derivedQueries is an array, where each element is an array as well.
mainQueries is an array.
> refactor(lodash): remove flatten

- src/SearchParameters/index.js
- src/functions/intersection.js
- test/spec/functions/intersection.js
I reverted the commit replacing intersection than copie the current implem into a new `intersection` function
I add something to avoid duplicates and some tests.
> fix(lodash/intersection): replace with custom implementation

- index.d.ts
- package.json
- yarn.lock
I ran prettier on the file, and also removed duplicates, but check to make sure it works as expected @samouss
> feat(typescript): move typings inline

- src/SearchParameters/index.js
- test/spec/SearchParameters/isDisjunctiveFacetRefined.js
> fix(isDisjunctiveFacetRefined): return false if not in disjunctiveFacets

- src/SearchParameters/index.js
- test/spec/SearchParameters/isExcludeRefined.js
- test/spec/algoliasearch.helper/incorrectFacetDefinition.js
same as #727, but changed the names
see #722
> fix(isExcludeRefined): remove error in favor of false

- src/SearchParameters/index.js
- test/spec/SearchParameters/isFacetRefined.js
Before we were throwing an error there, but we can better return false
see #722
> fix(isFacetRefined): return false if facet isn't declared

- documentation-src/metalsmith/content/upgrade.md
> docs(migration): mention changed methods

- src/SearchParameters/index.js
- test/spec/SearchParameters/getExcludeRefinements.js
There was no test for this yet
see #722
> fix(getExcludeRefinements): replace error by default value

- index.d.ts
see https://github.com/algolia/instantsearch.js/pull/4000
> fix(types): add state.removeNumericRefinement

- index.d.ts
- src/algoliasearch.helper.js
- test/integration-spec/helper.searchForFacetValues.js
- test/spec/algoliasearch.helper/searchForFacetValues.js
Similar to #889, but for search for facet values.
This makes sure that the facet values match between getFacetValues and searchForFacetValues, so that isRefined works as expected too.
> feat(sffv): escape value for use in refinements

- src/requestBuilder.js
- test/spec/requestBuilder.js
Jira: [FX-1621](https://algolia.atlassian.net/browse/FX-1621)
Currently when refining on a hierarchical menu, multiple queries are added to retrieve all the facet values for parent levels, allowing us to keep displaying the full list of the hierarchy.
There is a bug though, in which existing facet filters are not kept in the additional queries search parameters, which means that the hierarchy will display parent levels unrelated to the state of other widgets (see https://github.com/algolia/react-instantsearch/issues/3587).
This PR makes sure those facet filters are still set in the new queries.
> fix(facetValues): use existing facet filters in multi queries for hierarchical facet values

- .prettierrc
- jest.setup.js
- test/.eslintrc
- test/integration-spec/helper.derive.js
- test/integration-spec/helper.distinct.facet.js
- test/integration-spec/helper.filters.js
- test/integration-spec/helper.geo.js
- test/integration-spec/helper.highlight.js
- test/integration-spec/helper.insights.js
- test/integration-spec/helper.numerics.js
- test/integration-spec/helper.results.getFacetValues.js
- test/integration-spec/helper.searchForFacetValues.js
- test/integration-spec/helper.searchOnce.js
- test/integration-spec/helper.tags.js
- test/integration-utils.js
- do setup only once
- move setup to setupSimple in all cases
- increase timeout limit a little
before: longest test was ~1min (and failed on CI)
now: ~14sec
> test(integration): refactor to speed up

- renovate.json
We're not merging the PRs, so this is wasted work
> chore: delete renovate
